import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })
const defaultEndpoint = 'https://rickandmortyapi.com/api/character';
export async function getServerSideProps() {
  const rest = await fetch(defaultEndpoint);
  const data = await rest.json();
  return{
    props: {
      data
    }
  }
}

export default function Home({data}) {
  console.log(data)
  return (
    <>
      <Head>
        <title>Content Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      
      <div>
        <ul className='text-3xl '>
          <li>hello</li>
        </ul>
      </div>



      </main>
    </>
  )
}
