

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });
const defaultEndpoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps({query}) {
  const { id } = query;
  const rest = await fetch(`${defaultEndpoint}/${id}`);
  const data = await rest.json();
  return {
    props: {
      data,
    },
  };
}

export default function Character({ data }) {
  const {name, image, gender, location, species} = data;
  console.log('data', data)

  return (
    <>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="w-2/3 pt-32 m-auto text-center"><h1 className="text-4xl font-semibold">{name}</h1>

        <p>{gender}</p>
        <img src={image} alt={`name: ${name}`}/>
        
        </div>
        
        <Link href='/'>
        <button className="px-12 py-4 m-auto text-2xl font-semibold text-center bg-orange-500 border rounded-2xl border-solid-3">Bring me back</button>
        </Link>

      </main>
    </>
  );
}
